'use client'

import { useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { supabase } from '@/lib/supabase'
import { Goal, Quote, Transaction } from '@/lib/types'
import { holdingsByAsset, realized, realizedRows } from '@/lib/calculations'
import { Plus, RefreshCw, Target, Wallet, TrendingUp, Trash2, Pencil, LogOut, ArrowUpRight, ArrowDownRight, BarChart3, CircleDollarSign } from 'lucide-react'

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0)
const num=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:3}).format(n||0)
const pct=(n:number)=>`${n>=0?'+':''}${n.toFixed(2)}%`
const hasBackend=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)

const demoTxs:Transaction[]=[
 {id:'1',asset_type:'STOCK',symbol:'RELIANCE',name:'Reliance Industries',exchange:'NSE',tx_type:'BUY',quantity:25,price:1350,fees:30,trade_date:'2026-07-10'},
 {id:'2',asset_type:'STOCK',symbol:'HDFCBANK',name:'HDFC Bank',exchange:'NSE',tx_type:'BUY',quantity:40,price:810,fees:30,trade_date:'2026-07-15'},
 {id:'3',asset_type:'STOCK',symbol:'TCS',name:'Tata Consultancy Services',exchange:'NSE',tx_type:'BUY',quantity:10,price:3250,fees:25,trade_date:'2026-08-01'},
 {id:'4',asset_type:'STOCK',symbol:'TCS',name:'Tata Consultancy Services',exchange:'NSE',tx_type:'SELL',quantity:2,price:3450,fees:10,trade_date:'2026-09-05'},
 {id:'5',asset_type:'MF',symbol:'PPFAS',name:'Parag Parikh Flexi Cap Fund',tx_type:'BUY',quantity:245.63,price:81.45,fees:0,trade_date:'2026-09-05'},
 {id:'6',asset_type:'MF',symbol:'PPFAS',name:'Parag Parikh Flexi Cap Fund',tx_type:'BUY',quantity:60.22,price:83.03,fees:0,trade_date:'2026-09-15'},
]
const demoQuotes:Record<string,Quote>={RELIANCE:{symbol:'RELIANCE',price:1415,change:18.2,changePct:1.30,source:'Demo',asOf:new Date().toISOString()},HDFCBANK:{symbol:'HDFCBANK',price:875,change:-4.1,changePct:-0.47,source:'Demo',asOf:new Date().toISOString()},TCS:{symbol:'TCS',price:3480,change:22,changePct:0.64,source:'Demo',asOf:new Date().toISOString()}}

export default function Home(){
 const demo=!hasBackend
 const sb=demo?null:supabase()
 const [session,setSession]=useState<any>(demo?{demo:true}:null)
 const [txs,setTxs]=useState<Transaction[]>(demo?demoTxs:[])
 const [goals,setGoals]=useState<Goal[]>(demo?[{id:'g1',name:'₹10 Lakh Portfolio',target:1000000,target_date:'2030-12-31',starting_value:0}]:[])
 const [quotes,setQuotes]=useState<Record<string,Quote>>(demo?demoQuotes:{})
 const [tab,setTab]=useState('dashboard'); const [show,setShow]=useState(false); const [editing,setEditing]=useState<Transaction|null>(null); const [goalShow,setGoalShow]=useState(false); const [loading,setLoading]=useState(!demo)
 async function load(){if(!sb)return;setLoading(true);const {data:{session}}=await sb.auth.getSession();setSession(session);if(!session){setLoading(false);return}const [{data:t},{data:g}]=await Promise.all([sb.from('transactions').select('*').order('trade_date',{ascending:false}),sb.from('goals').select('*').order('target_date')]);setTxs((t||[]) as Transaction[]);setGoals((g||[]) as Goal[]);setLoading(false)}
 useEffect(()=>{if(!demo){load();const {data}=sb!.auth.onAuthStateChange(()=>load());return()=>data.subscription.unsubscribe()}},[])
 async function refreshQuotes(){if(demo){setQuotes({...demoQuotes});return}const hs=holdingsByAsset(txs);const symbols=hs.filter(x=>x.asset_type==='STOCK').map(x=>x.symbol);if(symbols.length){const r=await fetch('/api/quotes?symbols='+encodeURIComponent(symbols.join(',')));if(r.ok)setQuotes(await r.json())}}
 useEffect(()=>{if(txs.length){refreshQuotes();const id=setInterval(refreshQuotes,30000);return()=>clearInterval(id)}},[txs])
 const holdings=useMemo(()=>holdingsByAsset(txs),[txs])
 const stockValue=holdings.filter(h=>h.asset_type==='STOCK').reduce((s,h)=>s+h.quantity*(quotes[h.symbol]?.price||h.avg),0)
 const mfValue=holdings.filter(h=>h.asset_type==='MF').reduce((s,h)=>s+h.quantity*(h.avg),0)
 const invested=holdings.reduce((s,h)=>s+h.invested,0)
 const totalValue=stockValue+mfValue
 const unrealized=totalValue-invested
 const realizedGain=realized(txs)
 if(loading)return <main className="min-h-screen grid place-items-center">Loading your tracker…</main>
 if(!session)return <Auth/>
 const appProps={demo,sb,txs,setTxs,goals,setGoals,holdings,quotes,refreshQuotes,load}
 return <main className="min-h-screen"><header className="topbar"><div className="shell topbar-inner"><div><div className="brand">INDIA<span>INVEST</span></div><p className="muted tiny">Personal portfolio intelligence</p></div><div className="actions"><button className="btn btn-secondary" onClick={refreshQuotes}><RefreshCw size={16}/> Refresh</button>{demo?<span className="demo-pill">DEMO PREVIEW</span>:<button className="btn btn-secondary" onClick={async()=>{await sb!.auth.signOut();load()}}><LogOut size={16}/> Logout</button>}</div></div></header>
 <div className="shell page"><nav className="tabs">{[['dashboard','Overview'],['investments','Investments'],['realized','Realised P/L'],['goals','Goals']].map(([k,v])=><button key={k} className={'tab '+(tab===k?'active':'')} onClick={()=>setTab(k)}>{v}</button>)}</nav>
 {tab==='dashboard'&&<Dashboard value={totalValue} invested={invested} unrealized={unrealized} realizedGain={realizedGain} holdings={holdings} quotes={quotes} goals={goals} stockValue={stockValue} mfValue={mfValue}/>} 
 {tab==='investments'&&<Investments {...appProps} onAdd={()=>{setEditing(null);setShow(true)}} onEdit={(x)=>{setEditing(x);setShow(true)}} onDelete={async(id)=>{if(demo){setTxs(x=>x.filter(t=>t.id!==id));return}await sb!.from('transactions').delete().eq('id',id);load()}}/>}
 {tab==='realized'&&<Realized txs={txs}/>} 
 {tab==='goals'&&<Goals goals={goals} value={totalValue} invested={invested} onAdd={()=>setGoalShow(true)} onDelete={async(id)=>{if(demo){setGoals(x=>x.filter(g=>g.id!==id));return}await sb!.from('goals').delete().eq('id',id);load()}}/>}
 </div>
 {show&&<TransactionModal demo={demo} sb={sb} initial={editing} close={()=>setShow(false)} saved={(t)=>{setShow(false);if(demo)setTxs(x=>editing?x.map(y=>y.id===t.id?t:y):[t,...x]);else load()}}/>}
 {goalShow&&<GoalModal demo={demo} sb={sb} close={()=>setGoalShow(false)} saved={(g)=>{setGoalShow(false);if(demo)setGoals(x=>[...x,g]);else load()}}/>}
 </main>
}

function Auth(){const sb=supabase();const[email,setEmail]=useState('');const[pw,setPw]=useState('');const[signup,setSignup]=useState(false);const[err,setErr]=useState('');return <main className="min-h-screen grid place-items-center p-5"><div className="auth card"><div className="brand big">INDIA<span>INVEST</span></div><p className="muted mb-6">Private portfolio, SIP and goal tracking.</p><input className="input mb-3" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input mb-3" placeholder="Password" type="password" value={pw} onChange={e=>setPw(e.target.value)}/>{err&&<p className="text-rose-400 text-sm mb-3">{err}</p>}<button className="btn btn-primary full" onClick={async()=>{const r=signup?await sb.auth.signUp({email,password:pw}):await sb.auth.signInWithPassword({email,password:pw});if(r.error)setErr(r.error.message)}}>{signup?'Create account':'Sign in'}</button><button className="link-btn" onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Sign in':'New here? Create an account'}</button></div></main>}

function Dashboard({value,invested,unrealized,realizedGain,holdings,quotes,goals,stockValue,mfValue}:{value:number;invested:number;unrealized:number;realizedGain:number;holdings:any[];quotes:Record<string,Quote>;goals:Goal[];stockValue:number;mfValue:number}){const allocation=value?(stockValue/value*100):0;return <><div className="hero"><div><p className="eyebrow">PORTFOLIO OVERVIEW</p><h1>Track every rupee.<br/><span>See the bigger picture.</span></h1><p className="muted hero-copy">Stocks, mutual funds, SIPs, realised gains and long-term goals in one place.</p></div><div className="hero-stat"><span>Current portfolio</span><strong>{money(value)}</strong><small className={unrealized>=0?'positive':'negative'}>{money(unrealized)} unrealised</small></div></div><div className="grid md:grid-cols-5 gap-4 mb-6"><Metric label="Total invested" value={invested} icon={Wallet}/><Metric label="Current value" value={value} icon={CircleDollarSign}/><Metric label="Unrealised P/L" value={unrealized} icon={unrealized>=0?ArrowUpRight:ArrowDownRight} positive={unrealized>=0}/><Metric label="Realised P/L" value={realizedGain} icon={TrendingUp} positive={realizedGain>=0}/></div><div className="grid lg:grid-cols-3 gap-5"><div className="card p-5 lg:col-span-2"><div className="section-head"><div><h2>Current holdings</h2><p className="muted tiny">Live stock quotes refresh every 30 seconds</p></div></div><HoldingsTable holdings={holdings} quotes={quotes}/></div><div className="card p-5"><h2>Allocation</h2><div className="donut" style={{background:`conic-gradient(#60a5fa 0 ${allocation}%, #a78bfa ${allocation}% 100%)`}}><div className="donut-center"><strong>{allocation.toFixed(0)}%</strong><span>Stocks</span></div></div><div className="legend"><span><i className="dot blue"/>Stocks {allocation.toFixed(0)}%</span><span><i className="dot purple"/>Mutual funds {value?(mfValue/value*100).toFixed(0):0}%</span></div></div></div><div className="grid lg:grid-cols-2 gap-5 mt-5"><div className="card p-5"><div className="section-head"><h2>Goal progress</h2><Target size={18}/></div>{goals.length?goals.slice(0,3).map(g=>{const p=Math.min(100,value/g.target*100);return <div className="goal-mini" key={g.id}><div className="flex justify-between"><b>{g.name}</b><span>{p.toFixed(1)}%</span></div><div className="progress"><i style={{width:p+'%'}}/></div><p className="muted tiny">{money(value)} of {money(g.target)} · target {g.target_date}</p></div>}):<p className="muted">Create your first financial goal.</p>}</div><div className="card p-5"><div className="section-head"><h2>Portfolio mix</h2><BarChart3 size={18}/></div><div className="mix-row"><span>Stocks</span><strong>{money(stockValue)}</strong></div><div className="progress"><i style={{width:allocation+'%'}}/></div><div className="mix-row"><span>Mutual funds</span><strong>{money(mfValue)}</strong></div><div className="progress purple-progress"><i style={{width:(value?mfValue/value*100:0)+'%'}}/></div></div></div></>}
function Metric({label,value,icon:Icon,positive}:{label:string;value:number;icon:any;positive?:boolean}){return <div className="metric card"><div className="metric-icon"><Icon size={18}/></div><p>{label}</p><strong className={positive===undefined?'':positive?'positive':'negative'}>{money(value)}</strong></div>}
function HoldingsTable({holdings,quotes}:{holdings:any[];quotes:Record<string,Quote>}){return <div className="table-wrap"><table><thead><tr><th>Asset</th><th>Units</th><th>Avg cost</th><th>LTP / NAV</th><th>Value</th><th>P/L</th></tr></thead><tbody>{holdings.map(h=>{const q=quotes[h.symbol];const ltp=q?.price||h.avg;const val=h.quantity*ltp;const pnl=val-h.invested;return <tr key={h.symbol+h.asset_type}><td><b>{h.name}</b><div className="tiny muted">{h.symbol} · {h.asset_type==='STOCK'?h.exchange:'Mutual Fund'}</div></td><td>{num(h.quantity)}</td><td>{money(h.avg)}</td><td>{money(ltp)}</td><td>{money(val)}</td><td className={pnl>=0?'positive':'negative'}>{money(pnl)}<div className="tiny">{pct(h.invested?pnl/h.invested*100:0)}</div></td></tr>})}</tbody></table></div>}
function Investments({txs,holdings,quotes,onAdd,onEdit,onDelete}:{txs:Transaction[];holdings:any[];quotes:Record<string,Quote>;onAdd:()=>void;onEdit:(x:Transaction)=>void;onDelete:(id:string)=>void;demo:boolean;sb:any;setTxs:any;setGoals:any;goals:Goal[];refreshQuotes:any;load:any}){return <><div className="section-head mb-5"><div><p className="eyebrow">PORTFOLIO LEDGER</p><h2 className="page-title">Investments</h2><p className="muted">Every buy, SIP and sell is stored as a transaction.</p></div><button className="btn btn-primary" onClick={onAdd}><Plus size={17}/> Add investment</button></div><div className="card p-4 mb-5"><h3>Open positions</h3><HoldingsTable holdings={holdings} quotes={quotes}/></div><div className="card p-4"><h3 className="mb-3">Transaction history</h3><div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Asset</th><th>Units</th><th>Price / NAV</th><th>Fees</th><th>Actions</th></tr></thead><tbody>{txs.map(t=><tr key={t.id}><td>{t.trade_date}</td><td><span className={t.tx_type==='BUY'?'positive':'negative'}>{t.tx_type}</span></td><td><b>{t.name}</b><div className="tiny muted">{t.asset_type} · {t.symbol}</div></td><td>{num(t.quantity)}</td><td>{money(t.price)}</td><td>{money(t.fees)}</td><td className="actions-cell"><button onClick={()=>onEdit(t)}><Pencil size={15}/></button><button onClick={()=>onDelete(t.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></div></>}
function Realized({txs}:{txs:Transaction[]}){const rows=realizedRows(txs);return <><div className="section-head mb-5"><div><p className="eyebrow">EXITED POSITIONS</p><h2 className="page-title">Realised gains / losses</h2><p className="muted">FIFO cost basis is applied transaction-by-transaction.</p></div></div><div className="grid md:grid-cols-3 gap-4 mb-5"><Metric label="Total realised" value={realized(txs)} icon={TrendingUp} positive={realized(txs)>=0}/><Metric label="Realised transactions" value={rows.length} icon={BarChart3}/><Metric label="Winning exits" value={rows.filter(r=>r.gain>=0).length} icon={ArrowUpRight}/></div><div className="card p-4"><div className="table-wrap"><table><thead><tr><th>Date</th><th>Asset</th><th>Units sold</th><th>Sell price</th><th>Cost basis</th><th>Net proceeds</th><th>Gain / loss</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.date}</td><td><b>{r.name}</b><div className="tiny muted">{r.symbol}</div></td><td>{num(r.quantity)}</td><td>{money(r.sellPrice)}</td><td>{money(r.costBasis)}</td><td>{money(r.proceeds)}</td><td className={r.gain>=0?'positive':'negative'}>{money(r.gain)}</td></tr>)}</tbody></table></div></div></>}
function Goals({goals,value,invested,onAdd,onDelete}:{goals:Goal[];value:number;invested:number;onAdd:()=>void;onDelete:(id:string)=>void}){return <><div className="section-head mb-5"><div><p className="eyebrow">LONG-TERM PLAN</p><h2 className="page-title">Financial goals</h2><p className="muted">Turn your portfolio into measurable targets.</p></div><button className="btn btn-primary" onClick={onAdd}><Plus size={17}/> Add goal</button></div><div className="grid md:grid-cols-2 gap-4">{goals.map(g=>{const p=Math.min(100,value/g.target*100);const gap=Math.max(0,g.target-value);return <div className="card p-5" key={g.id}><div className="section-head"><h3>{g.name}</h3><button onClick={()=>onDelete(g.id)}><Trash2 size={16}/></button></div><div className="goal-number">{money(value)}</div><p className="muted">of {money(g.target)} target · {g.target_date}</p><div className="progress tall"><i style={{width:p+'%'}}/></div><div className="flex justify-between tiny mt-2"><span>{p.toFixed(1)}% complete</span><span>{money(gap)} remaining</span></div><div className="goal-note">Current invested cost: {money(invested)}</div></div>})}</div></>}

function TransactionModal({demo,sb,initial,close,saved}:{demo:boolean;sb:any;initial:Transaction|null;close:()=>void;saved:(t:Transaction)=>void}){const [f,setF]=useState<any>(initial||{asset_type:'STOCK',symbol:'',name:'',exchange:'NSE',tx_type:'BUY',quantity:'',price:'',fees:'0',trade_date:new Date().toISOString().slice(0,10),notes:''});const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));async function submit(){const id=initial?.id||crypto.randomUUID();const t:Transaction={...f,id,quantity:Number(f.quantity),price:Number(f.price),fees:Number(f.fees||0),exchange:f.asset_type==='MF'?null:f.exchange};if(demo){saved(t);return}const {data:{user}}=await sb.auth.getUser();if(!user)return;const payload={...t,user_id:user.id};if(initial)await sb.from('transactions').update(payload).eq('id',initial.id);else await sb.from('transactions').insert(payload);saved(t)}return <Modal title={initial?'Edit transaction':'Add investment'} close={close}><div className="modal-grid"><SelectField l="Asset type" v={f.asset_type} set={(v:any)=>set('asset_type',v)} opts={['STOCK','MF']}/><SelectField l="Transaction" v={f.tx_type} set={(v:any)=>set('tx_type',v)} opts={['BUY','SELL']}/><SelectField l="Exchange" v={f.exchange} set={(v:any)=>set('exchange',v)} opts={['NSE','BSE']}/><Field l="Symbol / MF code" v={f.symbol} set={(v:any)=>set('symbol',v.toUpperCase())}/><Field l="Name" v={f.name} set={(v:any)=>set('name',v)}/><Field l="Units / quantity" v={f.quantity} set={(v:any)=>set('quantity',v)} type="number"/><Field l="Buy/Sell price or NAV" v={f.price} set={(v:any)=>set('price',v)} type="number"/><Field l="Fees / charges" v={f.fees} set={(v:any)=>set('fees',v)} type="number"/><Field l="Transaction date" v={f.trade_date} set={(v:any)=>set('trade_date',v)} type="date"/></div><div className="modal-actions"><button className="btn btn-secondary" onClick={close}>Cancel</button><button className="btn btn-primary" onClick={submit}>Save investment</button></div></Modal>}
function GoalModal({demo,sb,close,saved}:{demo:boolean;sb:any;close:()=>void;saved:(g:Goal)=>void}){const[f,setF]=useState({name:'',target:'',target_date:new Date().getFullYear()+3+'-12-31'});async function submit(){const g:Goal={id:crypto.randomUUID(),name:f.name,target:Number(f.target),target_date:f.target_date,starting_value:0};if(demo){saved(g);return}const {data:{user}}=await sb.auth.getUser();if(!user)return;await sb.from('goals').insert({...g,user_id:user.id});saved(g)}return <Modal title="Create financial goal" close={close}><Field l="Goal name" v={f.name} set={(v:any)=>setF(x=>({...x,name:v}))}/><Field l="Target amount" v={f.target} set={(v:any)=>setF(x=>({...x,target:v}))} type="number"/><Field l="Target date" v={f.target_date} set={(v:any)=>setF(x=>({...x,target_date:v}))} type="date"/><div className="modal-actions"><button className="btn btn-secondary" onClick={close}>Cancel</button><button className="btn btn-primary" onClick={submit}>Create goal</button></div></Modal>}
function Field({l,v,set,type='text'}:{l:string;v:any;set:(v:any)=>void;type?:string}){return <label className="field">{l}<input className="input" type={type} value={v} onChange={e=>set(e.target.value)}/></label>}
function SelectField({l,v,set,opts}:{l:string;v:any;set:(v:any)=>void;opts:string[]}){return <label className="field">{l}<select className="input" value={v||opts[0]} onChange={e=>set(e.target.value)}>{opts.map(o=><option key={o}>{o}</option>)}</select></label>}
function Modal({title,close,children}:{title:string;close:()=>void;children?:ReactNode}){return <div className="modal-backdrop"><div className="modal card"><div className="section-head"><h2>{title}</h2><button onClick={close}>✕</button></div>{children}</div></div>}
